add solution homework 3
TliasheFF/react-course pull request #4
Opened 2024-01-26 12:45 UTC by TliasheFF

1. В компонент Dish добавить счетчик
2. Добавлены табы для ресторанов

2024-01-30 10:41 UTC, SArchieEdu requested changes

2024-01-30 10:41 UTC, SArchieEdu commented on src/components/restaurants/component.jsx
> +};
немного переусложнили. Покажу на разборе как сделать попроще. После разбора лучше переделать.

2024-01-31 06:28 UTC, TliasheFF commented on src/components/restaurants/component.jsx
> +};
переписал решение)
так же добавил страницу restaurant-page

2024-02-01 15:18 UTC, SArchieEdu approved these changes

2024-02-01 16:36 UTC, merged